### ISSUE TITLE
even faster switching with hotkey

### ISSUE THREAD

**Issue by emmanueltouzery** [daniellandau/switcher#10]
if the sorting of applications doesn't change within one session (if I understand bug #5 properly, the apps are sorted by the time they were opened so for sure the sorting wouldn't change in a session), what could be done is the following: when you display the list of apps, you could add a number of each app, for instance in a new column on the right.
Currently the columns are the icon then the window title. So we would add a new column, with a number.
Now we probably want to allow the users to type in digits to filter windows, so maybe then we use the F keys.. So let's say you want to switch with the app with number "6". You would just press "F6" and it would do the switching. Something like that.
And if the sorting is stable, you can remember for this session, this window is win-w f6. That one is win-w f4. That would be much faster than typing in the window title until the filtering is reduced to one window.
I'm wondering if you'd be considering implementing it or worst-case (for me ;-) ) accepting a PR to that effect?

**Comment by daniellandau** [comment]
Conversation happens in PR.

**Comment by daniellandau** [comment]
So something new landed in the PR, but if you still want stable shortcuts for predefined windows, I'd just do normal Gnome shortcuts (through keyboard settings) to simple bash scripts that run the awesome [wmctrl](https://sites.google.com/site/tstyblo/wmctrl) utility. For example you could have one for Emacs as `wmctrl -a emacs` and if you for example want to have Github open in one Firefox window you could do `wmctrl -a firefox github`
