### ISSUE TITLE
Switcher takes full screen width

### ISSUE THREAD

**Issue by abencheikh** [daniellandau/switcher#100]
Hey there !

I just installed Switcher, and I'm having an issue : whenever I invoke it, the Switcher box takes the full width of my screen and completely ignore the max width setting.
I'm using Gnome 3.36 with PaperWM if that helps...

![Screenshot from 2020-03-30 23-02-29](https://user-images.githubusercontent.com/9350941/77962184-6bc99a00-72db-11ea-9c79-357dd2a4105d.png)

Thanks!

**Comment by daniellandau** [comment]
That is a known issue that is fixed in master and waiting for review at extensions.gnome.org

**Comment by tuberry** [comment]
Just updated it for e.g.o. Switcher takes a fixed width(around 30%) now
![image](https://user-images.githubusercontent.com/17917040/78198500-557a3480-74bb-11ea-9d56-680c0797dec8.png)

**Comment by daniellandau** [comment]
Oh! Can you provide more details about your system? Like distribution etc.

**Comment by tuberry** [comment]
Sorry, It's ArchLinux/Gnome 3.36.1/Adwaita

**Comment by daniellandau** [comment]
Hmm, that's the same setup I have. Any other extensions?

**Comment by tuberry** [comment]
OK, I think I figure it out. 
It behave what it's supposed to be in the code. The box has a dynamic width according to the longest application name and making a compromise with the maxWidth.
What I want is a fixed width 60% but not a max width 60%. How about adding a Switch for that?
Thanks!

**Comment by daniellandau** [comment]
I'll have to think about that, maybe open a new issue for it.
