### ISSUE TITLE
Option to sort by "Most relevant" with "secondary" "Most recent" sorting

### ISSUE THREAD

**Issue by curusarn** [daniellandau/switcher#106]
I use "Most relevant" sorting because it feels more predictable.

However, I wish I could get a combination of "Most relevant" and "Most recent" sorting.

For, example when there is no query, the order of the windows seems random. It would be nice if there was an option to use "Most recent" as a secondary search.

Another example is when I type the name of the app such as "terminal". As a result, I get many windows that rank similarly using the "Most relevant" algorithm. 

In these situations, it would be nice to have a combination of "Most relevant" sort with a lower priority "Most recent" sort.

I like this to be another sorting option.

Thank you for your time and effort. Awesome extension.

**Comment by daniellandau** [comment]
Actually already "Most recent" is already used when there is no search query. I think what is tripping you up is that in "Most recent" the top two are always flipped as you might want to switch to the window you used before the one you have active right now, but if you want to just keep the currently active window active you can Esc out of the switcher.

The most relevant sorting could indeed be improved, any help with that is appreciated.

**Comment by curusarn** [comment]
Okay, that makes sense. Thank you.
