### ISSUE TITLE
Not Working on GNOME 3.36.1

### ISSUE THREAD

**Issue by darkfrog26** [daniellandau/switcher#107]
Just updated to 3.36.1 and the keyboard shortcuts no longer do anything.  I've tried uninstalling and re-installing, but to no avail.

**Comment by mejibyte** [comment]
Could this be a duplicate of https://github.com/daniellandau/switcher/issues/112?

**Comment by darkfrog26** [comment]
Sorry, forgot to close this as I was able to get it working again.
