### ISSUE TITLE
"Most relevant" ordering criteria should put longer matches first.

### ISSUE THREAD

**Issue by curusarn** [daniellandau/switcher#108]
For a "messe" query, the window with "Messenger in the title only comes in third. I would expect it to come in first because it is the longest match.

![switcher-bug](https://user-images.githubusercontent.com/10132717/82124425-41567200-979f-11ea-9260-068834e0a9ab.png)

**Comment by daniellandau** [comment]
I kind of feel that the best solution is to just get rid of the fuzzy match altogether. I don't use it as in my experience it leads to confusing results and it's hard to figure out why the order is what it is and at least for me if I typo a search it's easier to just fix that whenever it happens than deal with the fuzzy matcher results.

Could you try to disable the fuzzy matcher for a while and see if you'd be happier with the "most relevant" matches then?

**Comment by curusarn** [comment]
I switched from fuzzy to strict and I think I will be much happier with it. You are right that tolerating typos is nice but the strict matching is much more predictable.

Thanks.
