### ISSUE TITLE
Switcher has no background fill and appears in "error" state 

### ISSUE THREAD

**Issue by alexrgura** [daniellandau/switcher#112]
On Ubuntu 20.04, Gnome 3.36.3, X11.

Here are the extensions I have installed: 

![tweaks_screenshot](https://user-images.githubusercontent.com/6404824/88079335-2d364480-cb43-11ea-86a7-c86cb20532a5.png)

You can see the switcher appears in "error" mode. However, the switcher still functions properly, with one exception...

![switcher_screenshot](https://user-images.githubusercontent.com/6404824/88079382-3cb58d80-cb43-11ea-96e8-433a16864b75.png)

As you can see, there is no background fill. That means it is very hard to read when there are any applications on the desktop behind as the text is very hard to make out. 

I tried finding some logs to see if I could make out what is going on but I'm not that knowledgeable about X and Gnome, and various ways I could see if there's some error behind the scenes...

Let me know if theres any logs or steps I can take to help troubleshooting, if that would be helpful. 

I appreciate all the work that's gone into this, by the way, its a very very helpful extension.

EDIT: Switcher was installed directly from the gnome shell extension website, by the way, if that has any bearing on this.

**Comment by daniellandau** [comment]
What is the shell theme you are using?

**Comment by alexrgura** [comment]
I am using the default shell theme that comes with Ubuntu 20.04, I'm not
sure exactly which one that is.

**Comment by rcearfoss** [comment]
Same issue. Running PopOS default theme and shell. 
Also tried Adwaita same result

Here is the error I see 
JS ERROR: Extension switcher@landau.fi: Error: Property Gjs_ui_messageTray_NotificationPolicy.force-expanded is not writable

**Comment by javadr** [comment]
Same issue in Manjaro with Gnome 3.36.4 with default shell.
I also tested Adwaita but got the same result.

**Comment by mejibyte** [comment]
I was also able to reproduce this when I installed the extension from my browser at https://extensions.gnome.org/extension/973/switcher/.


I'm on Ubuntu 20.04 with Gnome 3.36.3.

Here's a stack trace that I found by running `sudo journalctl /usr/bin/gnome-shell`:


```
Aug 12 19:44:05 amber gnome-shell[73931]: JS ERROR: Extension switcher@landau.fi: Error: Property Gjs_ui_messageTray_NotificationPolicy.force-expanded is not writable
                                          showOne@/home/mejibyte/.local/share/gnome-shell/extensions/switcher@landau.fi/onboarding.js:53:19
                                          enable@/home/mejibyte/.local/share/gnome-shell/extensions/switcher@landau.fi/extension.js:541:16
                                          _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
                                          loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
                                          _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:599:18
                                          collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                          _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:574:19
                                          _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:608:18
                                          _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
                                          init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
                                          _initializeUI@resource:///org/gnome/shell/ui/main.js:257:22
                                          start@resource:///org/gnome/shell/ui/main.js:146:5
                                          @<main>:1:47
```

``

**Comment by mejibyte** [comment]
I have a workaround.

Commenting out line 53 in `$HOME/.local/share/gnome-shell/extensions/switcher@landau.fi/onboarding.js` and replacing it with this fixed it for me (I can open the extension and it seems to be working fine): 

* **Before**:
https://github.com/daniellandau/switcher/blob/84b83b5ae3d73932bb61bc3873c0cd5578fb7d44/onboarding.js#L53

* **After**:
```
  source.policy = new MessageTray.NotificationPolicy({});
```

I am not familiar with Gnome development at all, but I'm guessing this was an argument that used to exist and for some reason is no longer present in this API?

**Comment by mejibyte** [comment]
Looks like this is the culprit: https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/6aa1b817c9f65bad2a9af9b772d6876e30babf03

**Comment by rcearfoss** [comment]
> I have a workaround.
> 
> Commenting out line 53 in `$HOME/.local/share/gnome-shell/extensions/switcher@landau.fi/onboarding.js` and replacing it with this fixed it for me (I can open the extension and it seems to be working fine):
> 
>     * **Before**:
>       https://github.com/daniellandau/switcher/blob/84b83b5ae3d73932bb61bc3873c0cd5578fb7d44/onboarding.js#L53
> 
>     * **After**:
> 
> 
> ```
>   source.policy = new MessageTray.NotificationPolicy({});
> ```
> 
> I am not familiar with Gnome development at all, but I'm guessing `forceExpanded` was an argument that used to exist and for some reason it is no longer present in this API?

Can confirm this fixed it for me as well.

**Comment by alexrgura** [comment]
> > I have a workaround.
> > Commenting out line 53 in `$HOME/.local/share/gnome-shell/extensions/switcher@landau.fi/onboarding.js` and replacing it with this fixed it for me (I can open the extension and it seems to be working fine):
> > ```
> > * **Before**:
> >   https://github.com/daniellandau/switcher/blob/84b83b5ae3d73932bb61bc3873c0cd5578fb7d44/onboarding.js#L53
> > 
> > * **After**:
> > ```
> > 
> > 
> > ```
> >   source.policy = new MessageTray.NotificationPolicy({});
> > ```
> > 
> > 
> > I am not familiar with Gnome development at all, but I'm guessing `forceExpanded` was an argument that used to exist and for some reason it is no longer present in this API?
> 
> Can confirm this fixed it for me as well.

After making this change it *appears* that the fill is back and it looks normal. However, after commenting out that line the application now crashes as soon as I type a letter in the search bar.  Similar to  #111 . To be fair it has been inconsistent with the behavior after I uninstall and reinstall the application so I'm not sure if this specific fix changed much.

**Comment by daniellandau** [comment]
Version in master should work, and it'll get to extensions.gnome.org once it passes review.

**Comment by mejibyte** [comment]
Awesome, thanks a lot @daniellandau!
