### ISSUE TITLE
It doesn't work on Wayland

### ISSUE THREAD

**Issue by xzj8b3** [daniellandau/switcher#113]
I installed defaulth with ext4 but on Wayland switcher doesn't seem to go... is it possible to upgrade by resolving?

Using Fedora 32 with Gnome-Shell 3.36.4

**Comment by felipehw** [comment]
I'm using this extension in a Gnome 3.36.4 + Wayland + Fedora 32 without problems ...

**Comment by xzj8b3** [comment]
> I'm using this extension in a Gnome 3.36.4 + Wayland + Fedora 32 without problems ...

with Ext4 a m'è not go ... I left defaulth installation

**Comment by xzj8b3** [comment]
> I'm using this extension in a Gnome 3.36.4 + Wayland + Fedora 32 without problems ...

![Schermata da 2020-07-26 23-17-11](https://user-images.githubusercontent.com/26720956/89102194-08758300-d407-11ea-8f4f-0d47d76be7a0.png)

![Schermata da 2020-07-27 14-59-34](https://user-images.githubusercontent.com/26720956/89102197-0e6b6400-d407-11ea-8a8e-6b974c82901e.png)


Ich habe in Ext4 installiert, vielleicht eine kompatiblere Erweiterung in Btrfs, aber es sollte trotzdem gehen!!!

**Comment by xzj8b3** [comment]
> I'm using this extension in a Gnome 3.36.4 + Wayland + Fedora 32 without problems ...

![Schermata da 2020-08-01 14-58-43](https://user-images.githubusercontent.com/26720956/89535342-9af69780-d7f6-11ea-81cc-fc87eacee009.png)
no...I don't think it works on Wayland or Xorg which is pretty weird but it doesn't work and the system has just been reinstalled!!!

**Comment by felipehw** [comment]
As you can see at my picture ... the Switcher is open and I have my configs visible:

Switcher: version 28
Fedora: Silverblue 32.20200805.0
GNOME: 3.36.4
Windowing System: Wayland

![Untitled](https://user-images.githubusercontent.com/4523897/89541003-2ad71a00-d7d4-11ea-8395-31759e054bf3.jpg)

**Comment by daniellandau** [comment]
I'm not sure what the issue here is or if there is one with switcher. Please open a new issue if there are still problems.
