### ISSUE TITLE
Window only visible while holding down hotkey

### ISSUE THREAD

**Issue by krmax44** [daniellandau/switcher#114]
I have Switcher configured with `Alt + Space` and `Ctrl + Alt + Space`. When I press one of those shortcuts, the window blinks open for a second, but vanishes again once I release the keys, which makes typing in things impossible.

**Comment by daniellandau** [comment]
I'll look into that, but I suggest you use some other combination in the meantime.

**Comment by krmax44** [comment]
@daniellandau Unfortunately, all key combinations cause this issue

**Comment by daniellandau** [comment]
Oh, even basic super+alfabet key?

**Comment by krmax44** [comment]
yeah...

**Comment by krmax44** [comment]
After a reboot, it is now gone. :thinking: :thinking: :thinking:

**Comment by daniellandau** [comment]
Please open a new issue if the problem comes back.
