### ISSUE TITLE
Gnome 3.38

### ISSUE THREAD

**Issue by ZeChArtiahSaher** [daniellandau/switcher#129]
After updating to 3.38, switcher on my multi-monitor setup started to ignore main monitor and always spawn at left-most one.
Example: https://i.imgur.com/HwByFH4.png

**Comment by daniellandau** [comment]
This is fixed by https://github.com/daniellandau/switcher/commit/cdc1e2045f104f05302dee270c0e68e50f688ef7. It's now on the review queue at extensions.gnome.org
