### ISSUE TITLE
launcher mode doesn't work in Gnome 3.38.4

### ISSUE THREAD

**Issue by javadr** [daniellandau/switcher#134]
At First, thank you for your very useful and lovely extension, I can't imagine Gnome without this. 

Secondly, yesterday I updated the Gnome to 3.38.4 (in Manjaro) and then the switcher. But after that, I have no access to the launcher mode, I mean pressing both super+x or super+w just opens it in switcher mode and I am not able to switch between two modes with Ctrl+Space/Ctrl+Tab.

I didn't find any issue in the journalctl's output. I have no idea how to handle it.

**Comment by daniellandau** [comment]
There is no separate mode anymore. You can launch and switch from the one single mode.

**Comment by javadr** [comment]
Thank you for your fast reply. 
I've been using your extension since 2-3 years ago and I am so familiar with its modes. 
But after updating to Gnome 3.38.4 and switcher 32, I am not able to switch between launcher/switcher modes. The extension just runs in switcher mode. I think it is a Gnome issue, not the app as Gnome does not load a new instance of nautilus for example.

As below shows, I have no way to switch!
![Screenshot from 2021-03-02 12-20-20](https://user-images.githubusercontent.com/1178221/109622661-9b1f0180-7b51-11eb-87c8-d19752e330e4.png)

**Comment by daniellandau** [comment]
You can do ctrl+enter to launch new instances of apps that are already open. I should probably add a new onboarding text about the changes (although I don't know if anybody reads them)

**Comment by javadr** [comment]
Thanks a million, It really helps. :+1: 
I did read it several times but no clue about ctrl+enter.  

P.S.
Ctrl+Enter doesn't close the popup, is there any hack to apply in the code to run a new instance and then close the popup.
