### ISSUE TITLE
Change menu size

### ISSUE THREAD

**Issue by xzj8b3** [daniellandau/switcher#138]
Hi, but Modify menu size from what strings should I do it? I wanted to make them a little more compact could you help me please!

**Comment by daniellandau** [comment]
You can change the font and icon size in the preferences.

**Comment by xzj8b3** [comment]
> You can change the font and icon size in the preferences.

What if I want to make the menu a little smaller and more compact?

**Comment by daniellandau** [comment]
I don't know what you mean.

**Comment by xzj8b3** [comment]
> I don't know what you mean.

It is giving me problems, I had to uninstall it...I messed with the key combination and it doesn't work anymore, but also in startup it conflicts with other extensions!!!

**Comment by xzj8b3** [comment]
> I don't know what you mean.

I put Cowerflow and antimations and desktops go smoothly...it's just Switcher creates conflicts!!!

**Comment by daniellandau** [comment]
I still don't understand. If there's an actual error please open a new issue with the error messages you get and instructions on how to reproduce.

For changing the size of the switcher there are options in the preferences to do that.
