### ISSUE TITLE
Support for Gnome 40

### ISSUE THREAD

**Issue by felipehw** [daniellandau/switcher#139]
This is the only extension that I need to survive in a Gnome environment.
It will be ported for Gnome 40? :dancing_men:

**Comment by daniellandau** [comment]
Yes, work is ongoing and almost done https://github.com/daniellandau/switcher/tree/gnome-40

**Comment by daniellandau** [comment]
Implemented in https://github.com/daniellandau/switcher/pull/140, will submit to extensions.gnome.org next and it will show up there soonish.
