### ISSUE TITLE
Feature Request: Open new window

### ISSUE THREAD

**Issue by sha-red** [daniellandau/switcher#142]
I'd like to have an option to open a new window for a launchable application even if this application already has windows open.

I mostly used switcher to open new windows for applications already running, e.g. Firefox; instead of right-clicking the application in the dock. Unfortunately this feature disappeared with removing the launcher mode.

**Comment by daniellandau** [comment]
You can press ctrl-enter to do that. There's currently no good way to notify users of new features. The old notification based one broke on Gnome 40 and I don't think it was very effective to begin with.
