### ISSUE TITLE
Could this be updated to only show apps that are running

### ISSUE THREAD

**Issue by GrantByrne** [daniellandau/switcher#147]
I don't have too much use for an app that launches windows. I normally just hit super and type the app name.

I would like an option to allow me to just search through the apps that are currently open.

Great plugin. I'm here because I had issues using Rofi.

**Comment by daniellandau** [comment]
The open windows are always sorted before launchable apps

**Comment by GrantByrne** [comment]
That's fair. This meets my needs. I think I have another request, but I'll read the docs first before opening up another ticket to make sure it isn't already there.
