### ISSUE TITLE
Gnome 42 support?

### ISSUE THREAD

**Issue by lkraav** [daniellandau/switcher#153]
It turns out I don't even know how to use Gnome Shell without Switcher :)

Has anybody here looked into if there are any refactoring necessary for Gnome 42 compatibility?

**Comment by daniellandau** [comment]
Yes there are. I've got it almost ready, but not quite yet.

**Comment by lkraav** [comment]
> Yes there are. I've got it almost ready, but not quite yet.

Thanks. I was looking for a branch or a PR, like Gnome 40 compat work had, but couldn't find anything. I guess you're working on it locally.

**Comment by daniellandau** [comment]
Yes, it's going to be a single commit.

**Comment by daniellandau** [comment]
Got it finished, now on https://github.com/daniellandau/switcher/commit/af1385fe5adecdd8a051de53fd17b03c7292b8d8 and at e.g.o.

I'm glad you like it, I don't know how to use Gnome Shell without it either :)
