### ISSUE TITLE
Please update for GNOME 43.

### ISSUE THREAD

**Issue by scottbeamer** [daniellandau/switcher#156]
GNOME 43 is came out in September and this extension is not compatible.

Thank you.

**Comment by farhanmry** [comment]
you can manually change shell-version in metadata.js to 43 as workaround

**Comment by scottbeamer** [comment]
Where do I find this file?

Thanks.

**Comment by farhanmry** [comment]
in `~/.local/share/gnome-shell/extensions/switcher@landau.fi`

**Comment by hzhangxyz** [comment]
I try to change `shell-version` from `42` to `43` in `metadata.json`, it seems working well.

**Comment by daniellandau** [comment]
Thank you all for testing, now on extensions.gnome.org
