### ISSUE TITLE
Gnome 45 support

### ISSUE THREAD

**Issue by deadlymcgee** [daniellandau/switcher#160]
Thank you for this great extension - couldn't imagine switching windows in Gnome without it!

Just wanted to check how the work to address the breaking changes in Gnome 45 is going?

**Comment by tmahmood** [comment]
Same here! Waiting for update

**Comment by leducvin** [comment]
Hey, I created a pull request #161 for this. I enjoy this extension very much and couldn't wait :)

Hopefully @daniellandau will be able to review and merge at some point.

In the meantime if you want to try my fork, it's available at https://github.com/leducvin/switcher/tree/master

**Comment by nforced** [comment]
@leducvin Great work! Can't wait for this to be merged @daniellandau

**Comment by deadlymcgee** [comment]
Have been running the Gnome 45 version for the last couple of days and everything is working as expected. Thanks @leducvin and @daniellandau :smile:
