### ISSUE TITLE
Not Compatible Gnome 46.1

### ISSUE THREAD

**Issue by JesseCSlater** [daniellandau/switcher#167]
Switcher is not compatible with Gnome 46.1 which is the current version shipped with Fedora 40.

**Comment by daniellandau** [comment]
Something seems to have gone wrong with the upload to extensions.gnome.org of the compatible version. I'll check that today.

**Comment by arisuv** [comment]
Working fine for me Gnome 46.1 with Fedora 40

**Comment by rvdwijngaard** [comment]
any update on this?

**Comment by JesseCSlater** [comment]
Switcher still appears incompatible with Gnome 46 through the Gnome extensions store. The latest version available for download is switcher version 39 for Gnome 45. I am currently on a fully up to date Fedora system with Gnome 46.2 on Wayland.

**Comment by daniellandau** [comment]
Didn't have time to check it "later today", but now it's fixed on extensions.gnome.org with a new update.
