### ISSUE TITLE
extension does not work with gnome 47.0

### ISSUE THREAD

**Issue by rvdwijngaard** [daniellandau/switcher#170]
Plugin does not work with gnome 47.0

**Comment by fingerblaster** [comment]
The settings of extension switcher@landau.fi had an error:
```
Error: Argument to the constructor of Popover should be a plain JS object with properties to set

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:39:56
  buildOnboarding@file:///var/home/s6mchn_/.local/share/gnome-shell/extensions/switcher@landau.fi/prefs.js:363:19
  buildWidgets@file:///var/home/s6mchn_/.local/share/gnome-shell/extensions/switcher@landau.fi/prefs.js:97:44
  buildPrefsWidget@file:///var/home/s6mchn_/.local/share/gnome-shell/extensions/switcher@landau.fi/prefs.js:23:3
  fillPreferencesWindow@file:///var/home/s6mchn_/.local/share/gnome-shell/extensions/switcher@landau.fi/prefs.js:411:22
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:39:24
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:24:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:15:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:138:33
  async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:125:14
  _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  
```

**Comment by maxfridbe** [comment]
Ping also having this issue:

> Error: Argument to the constructor of Popover should be a plain JS object with properties to set
> 
> Stack trace:
>   _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:39:56
>   buildOnboarding@file:///var/home/maxfridbe/.local/share/gnome-shell/extensions/switcher@landau.fi/prefs.js:363:19
>   buildWidgets@file:///var/home/maxfridbe/.local/share/gnome-shell/extensions/switcher@landau.fi/prefs.js:97:44
>   buildPrefsWidget@file:///var/home/maxfridbe/.local/share/gnome-shell/extensions/switcher@landau.fi/prefs.js:23:3

**Comment by malcolmredheron** [comment]
@daniellandau: might you update this soon? I love your extension (it and PaperWM are critical for me) and am holding off updating to Gnome 47 because of this

**Comment by bilboquet** [comment]
> @daniellandau: might you update this soon? I love your extension (it and PaperWM are critical for me) and am holding off updating to Gnome 47 because of this

Same here, these 2 extensions are central to my workflow, I love and need them.
So thanks to Daniel

**Comment by malcolmredheron** [comment]
I found https://extensions.gnome.org/extension/4412/advanced-alttab-window-switcher/ and switched to it. It's a bit of work because it has a million options, but it works fine and says that it supports Gnome 47 (though I haven't tried upgrading again)

**Comment by daniellandau** [comment]
Sorry for the delay everyone. I'll be still out of the country this week, but next week I'll be able to do a release.

**Comment by daniellandau** [comment]
Now available on e.g.o
