### ISSUE TITLE
No screen blackout

### ISSUE THREAD

**Issue by berarma** [daniellandau/switcher#2]
Most/all similar extensions (see the Howdoi extension) blackout all screens when showing the main dialog. I'm working with two monitors and when the window selector is shown, it's not obvious that the screens are locked. It would be a big visual improvement that all screens were obscured when the dialog is shown.

**Comment by daniellandau** [comment]
Sorry for taking so long to respond.

For example the Alt+F2 dialog has a halo effect to give more focus to the dialog, but the system default Alt-Tab doesn't dim the screen in any ways. I kind of feel that as the switcher should come and go away quickly (that's the point) that maybe any effect is not needed, but I'm willing to take in code that makes it optionally obfuscate the screen.

**Comment by wbolster** [comment]
i would be very annoyed if this extension blacks out my screen. it would result in a lot of flickering which hurts my eyes. the alt-tab switcher doesn't black out the screen either.

though i see the use case for the multi-monitor setup. perhaps only blacking out monitors that do NOT display the chooser is a better ui approach.

**Comment by berarma** [comment]
I agree. It could have a delay so it only happens when the switcher stays on for a while.

It's not that I'm looking for the visual effect, but rather trying to avoid the confusion when the switcher is on one screen while the others seem frozen. Perhaps having the switcher disappear when clicking anywhere on the screen would be a better option.

**Comment by daniellandau** [comment]
It absolutely should disappear when clicking on any point of the screen, even on multimonitor. That's a bug. Could you post another issue with your screen configuration (orientation and sizes of screens, etc)?

**Comment by berarma** [comment]
Done: #34
