### ISSUE TITLE
Support clicking on a window list item

### ISSUE THREAD

**Issue by iyosifov** [daniellandau/switcher#23]
Directly clicking on a window in the list appears to just close the list. It should switch to the clicked window instead. This is both the intuitively expected behavior and more efficient than keyboard navigation eg. after narrowing down a long list of windows with a search. 

This problem aside, the extension is awesome. Thanks.

**Comment by daniellandau** [comment]
I agree. The extension grabs all input so I want to be absolutely certain that all users are able to close it and that's why clicking does just that. Better would be to change the highlight on hover and activate window on click.

Pull requests are welcome.

**Comment by daniellandau** [comment]
This is now implemented in https://github.com/daniellandau/switcher/commit/cf326ceddcc191febf0e72713e940b52d2abaa1e.
