### ISSUE TITLE
Add option to only switch windows on active workspace

### ISSUE THREAD

**Issue by jwarkentin** [daniellandau/switcher#25]
I tend to have a large list of windows open and generally I work between windows on a single workspace at a time as I'm jumping between code and terminals on one workspace and browsers on another. It's really frustrating when I accidentally select a browser while I'm on my workspace with my code and it switches to a different workspace. It would be nice to have an option to only show and switch between windows on the active workspace.

**Comment by daniellandau** [comment]
Done in https://github.com/daniellandau/switcher/commit/9d0759ac4c5514234c7e62ce156167adc751f1e9, will arrive in extensions.gnome.org after review.

Thanks for the suggestion! This doesn't suit my workflow at all, but I can see how it's useful for yours.

**Comment by jwarkentin** [comment]
It's perfect, thank you!
