### ISSUE TITLE
Assigning <Super><Space> shortcut === "Disabled"

### ISSUE THREAD

**Issue by lkraav** [daniellandau/switcher#26]
I've removed this shortcut from Gnome default input source switching.

But `switcher` doesn't seem to recognize it. Your thoughts?

**Comment by daniellandau** [comment]
Does another extension use that binding? At least shellhsape has that binding by default if I remember correctly. Super+Space works for me.

**Comment by lkraav** [comment]
I'm using `gnome-3.18` for now btw. Upgrading to 3.20 soon. But right now with wayland, shortcut editor suffers from https://bugzilla.redhat.com/show_bug.cgi?id=1213113 where `<Super>` cannot be input at all. So I'm using `dconf-editor` to modify the shortcut. After entering `<Super><Space>`, `switcher` shows "Disabled" as result. Setting the shortcut back to `<Super>W` or similar works perfectly.

**Comment by daniellandau** [comment]
You want to use `<Super>space`, it seems. At least that's what `dconf-editor` shows for me (under X) when I input that combination through the GUI.

**Comment by lkraav** [comment]
Yey! For once, my own brainfart instead of "patches needed" :) Tyvm sir
