### ISSUE TITLE
Styling suggestions

### ISSUE THREAD

**Issue by berarma** [daniellandau/switcher#3]
This is a suggestion for enhancement.

While the text in the input box is pretty small, the window titles are really big on my screen. I think I'd like it better if the title texts a little smaller. They would fit better too, some titles are long and I like having the title shown there.

Also, I normally use the icons to quickly identify the window I want to switch to, and just in case there's more than one I will look for the title. I'd like that the icons were a bit bigger and grouping the windows by app would make it easier for me to visually find what I want.

Best regards.

**Comment by vltr** [comment]
I just mentioned that on the extension page on gnome.org. Here it comes a copy, for the register: "Anyway, would you mind providing more information to customize itss look'n'feel, so a theme could carry its stylesheet to match? That would be awesome :) Thanks a lot!"

cheers!

**Comment by sljunkie** [comment]
This extension idea is pretty nifty. But on small displays the displayed font is *huge* - the possibility of changing the font and size would be a huge improvement.

**Comment by daniellandau** [comment]
Sorry for taking so long to respond.

So in the current version you can customize the font size and screen real estate. I don't want grouping by app by default, but I have nothing against it as an option. Currently the icon size is tied to the text size.

**Comment by daniellandau** [comment]
The Pull Request from nevesnunes fixes most of the requests. If you still want grouping by app, please open another Issue (or provide it as a Pull Request).
