### ISSUE TITLE
toggle when global shortcut is pressed twice

### ISSUE THREAD

**Issue by wbolster** [daniellandau/switcher#30]
currently, ctrl-tab and ctrl-space switch between apps/window selection.

it would be great if pressing the global shortcut twice would toggle between the two as well. right now this doesn't do anything.

**Comment by daniellandau** [comment]
This is actually not technically trivial (although it might be doable). I'd be happy to have that, though.

**Comment by wbolster** [comment]
hmm. the hotkey doesn't generate an event when the overlay is active?

**Comment by daniellandau** [comment]
Yup. We could get the hotkey from settings ourselves and handle it, but I'm not sure that's worth the effort. Or there might be some other way I'm missing.

**Comment by matejmosko** [comment]
If it is more possible, I would vote for closing the switcher/launcher when pressing global shortcut twice. It works this way with  similar applications shell, synapse, windows start menu... it would be much nicer to switch between launcher and switcher with left and right arrows.

**Comment by olejorgenb** [comment]
> Yup. We could get the hotkey from settings ourselves and handle it, but I'm not sure that's worth the effort. Or there might be some other way I'm missing.

Mutter to the rescue :smiley: 

`global.display.get_keybinding_action(event.get_key_code(), event.get_state())` returns the mutter action id corresponding to the clutter key-event.

`Main.wm.addKeybinding` returns the mutter action id of the keybinding registered.

(see gnome-shell's switchPopup for example usage)

**Comment by daniellandau** [comment]
Thanks for the tip @olejorgenb, this is now implemented in https://github.com/daniellandau/switcher/commit/9d83223ecac09a66bde5aa6948d93814c4d3d407
