### ISSUE TITLE
use key-press-event instead of key-release-event

### ISSUE THREAD

**Issue by wbolster** [daniellandau/switcher#32]
it would be better to use `key-press-event` instead of `key-release-event`.

by doing so, keys repeat while holding them down. this means it becomes to possible to hold down ctrl-n or ctrl-p (or arrow keys) to navigate the list.

also, the whole interaction becomes much snappier. with `key-release-event` there's a clearly perceptible delay that just does not feel right. it's hard to explain, try it! :)

note that there is one feature that somehow stops working when switching to `key-press-event`: numeric shortcut keys no longer result in selection; instead the numbers appear in the text entry.

**Comment by daniellandau** [comment]
Also the basic filtering doesn't work with `key-press-event`, but maybe we could have both and do on key-press the things that work with that (such as navigation) and on key-release the rest.

**Comment by wbolster** [comment]
ouch, pressing enter stops working indeed, making the whole thing useless. still the snappiness is worth it imho.

**Comment by daniellandau** [comment]
Fixed in https://github.com/daniellandau/switcher/commit/500ea672db3b7bc140309b291df1e0c9c3d59ad5.

Thanks!
