### ISSUE TITLE
fade in/out

### ISSUE THREAD

**Issue by wbolster** [daniellandau/switcher#33]
my eyes would be very happy if the popup quickly fades in and out instead of suddenly obscuring a big part of my screen.

**Comment by daniellandau** [comment]
I think the same comparison with Alt-Tab as in https://github.com/daniellandau/switcher/issues/2 applies here too (that is, don't fade here as alt-tab doesn't fade either), but I don't mind if somebody wants to make this an optional extra.

**Comment by wbolster** [comment]
i just reduced the font size so that the overlay occupies a significantly smaller portion of my screen. that also helps a lot.

some background: the main issue here is that sudden flickering is painful, especially with high contrast (e.g. when the underlying window is light), and i am looking for ways to make it less annoying. one way is to reduce the area. another is to make it smoother.

**Comment by daniellandau** [comment]
Thanks to @ounos, this is now implemented and will find its way to a release soon.
