### ISSUE TITLE
Switcher doesn't disappear when clicking on secondary screen

### ISSUE THREAD

**Issue by berarma** [daniellandau/switcher#34]
From issue #2. I have two screens horizontally placed, and the order is: Main, Secondary. They're exactly the same, resolution 1920x1200. I'm using Gnome 3.14 on Debian Jessie.

The switcher opens in the main screen, then if I click anywhere on the secondary screen nothing happens. Secondary screen seems frozen and main screen stays with the switcher on.

**Comment by daniellandau** [comment]
This should be fixed in https://github.com/daniellandau/switcher/commit/02e28b4bb34ca7fc9b8abe07ac1ee12f83a34195.
