### ISSUE TITLE
Keyboard layout switching (changing input language) doesn't work

### ISSUE THREAD

**Issue by jvlad** [daniellandau/switcher#36]
After switcher have been launched it is not possible to toggle between different keyboard layouts. Would be great to fix it.

Change_layout _shortcut I use: `super+space`

**Comment by daniellandau** [comment]
You can't switch layouts inside alt-tab either. Can't you just close the switcher, switch to the layout you want and then reopen?

**Comment by ItamarShDev** [comment]
The question is:
Can we switch keyboard layout while in gnome overview search box?

**Comment by daniellandau** [comment]
Had to dig around in Gnome Shell sources, but turns out the solution is easy once you find it. This is fixed in https://github.com/daniellandau/switcher/commit/56eaa7af65b4313e93ba858800684f50d7ff1ce8.
