### ISSUE TITLE
Open Switcher on active monitor instead of always the primary one

### ISSUE THREAD

**Issue by tsdh** [daniellandau/switcher#43]
I work with two identical monitors.  The left is the primary one (where I have different workspaces) and the right is the secondary one.

Right now, when I invoke Switcher the popup is always on the primary monitor.  It would be much better for me if it popped up on the monitor containing the currently focused window because that's where I am looking at.

Other than that, Switcher is really, really nice.  Keep up the good work!

**Comment by daniellandau** [comment]
I think always on primary is a good default, but I wouldn't mind a configuration option for "on active monitor".
