### ISSUE TITLE
search english names as well

### ISSUE THREAD

**Issue by wbolster** [daniellandau/switcher#45]
it would be nice if the application search also used the original (untranslated) application name. the overview search bar seems to do this already. additionally, also use the `Exec=...` value. all of these are in the `.desktop` files.

**Comment by daniellandau** [comment]
If this is implemented, I think the original name and Exec value that are matched on should also be visible then.

**Comment by wbolster** [comment]
nah, i do not think that is necessary. this is about being able to type "evince" and have "document viewer" show up. this works in the overview search, and it would be great if that would work in switcher as well.

**Comment by olejorgenb** [comment]
I'm willing to attempt an PR if I read @daniellandau correct in that there's not resistance to the idea it self(?)

I agree with @wbolster that it's not really necessary to visualize the match, though ideally it would be visible somehow.

**Comment by daniellandau** [comment]
That would be nice. I've tested locally a branch where the executable and original name are searched (and shown) as well. I like it, but what it's missing is toggles in settings to enable/disable the extra infos.

I pushed my work in progress at https://github.com/daniellandau/switcher/compare/original-and-executable-names?expand=1
