### ISSUE TITLE
Disabling "Tipp of the day" notification

### ISSUE THREAD

**Issue by michael-rapp** [daniellandau/switcher#46]
After each reboot, a notification, which shows a hint about the extension's usage, is shown. I don't want this notification to be shown again. But even if I click the notification's "do not show again" button, another hint is shown after the next reboot. I've not found an option to permanently disable the notifications in the extension's settings either. I would really appreciate such an option to be available. Thank you!

**Comment by daniellandau** [comment]
There are five notifications total in the current version and more will appear slowly when there is some new non-obvious functionality. You can cycle through them quickly by doing Alt+F2 and typing restart in the box or logging out and logging back in repeatedly or even disabling and enabling the extension repeatedly. You can also use dconf-editor to manually set status of all current messages to viewed, but new messages with new updates will still show up.

I put a lot of thought into how and when to show the messages and straight after installation or after logging in seemed like a good and non-intrusive time as you are not in the middle of anything while logging in and focusing on the extension anyways when installing or updating. Even then the notification banner is visible only for the default four seconds if you don't engage with it.

I hope that answers your concerns.

**Comment by michael-rapp** [comment]
Thank you for the clarification. I found it kind of confusing, that yet unshown notifications still popped up after I clicked the "do not show again" button. I was expecting, that no notifications will be shown at all, after choosing that option.
