### ISSUE TITLE
Switcher Quick View

### ISSUE THREAD

**Issue by ItamarShDev** [daniellandau/switcher#47]
Is it possible that the switcher will have a "quick peak" option?
By that I mean that when you scroll the open apps list in the switcher, the selected app will be shown in the background.
If I press "Return" the app is going to the foreground, and if not i will be returned to my currently open app

This idea came to me because I use Sublime Text, and there is a great features in the editor, where you can peak a file by pressing Ctrl+P and iterating though the list.

I imagine this is very hard and maybe impossible to accomplish on a desktop environment, yet it could be a very cool and productive for work environments - where you sometimes iterate through a lot of open programs

Thank you in advance

**Comment by daniellandau** [comment]
I suppose that could be technically possible, as some native tools show live thumbnails of applications. That would require some thought into how exactly it should work.
