### ISSUE TITLE
Do not fallback to application launcher

### ISSUE THREAD

**Issue by Barthalion** [daniellandau/switcher#48]
I recently upgraded the extension to version 14. I noticed that once it fails to find matching window, it switches to application launcher. Can this behavior is disabled?

**Comment by daniellandau** [comment]
At the moment, no. Do you have a specific reason why you wouldn't want that? There is a previous discussion about this functionality here: https://github.com/daniellandau/switcher/issues/31

**Comment by Barthalion** [comment]
I use rofi for launching regular commands, desktop launchers and copying password-store content, and Switcher only for window switching. I guess that doesn't make me a regular Gnome user…

It would be nice to have it configurable, but it's nothing essential. Now when I think about it, It makes sense for vast majority of users. I think I will just get used to it. Thanks. :)
