### ISSUE TITLE
Tips notifications spam

### ISSUE THREAD

**Issue by cbednarski** [daniellandau/switcher#50]
Heyo! Thanks for writing this plugin. I'm just moving over from MacOS to Gnome 3 and was missing Alfred a bit; switcher is a pretty good stopgap!

I'm getting a bit of notification spam from switcher tips. I don't know how to turn these off (I did not see a setting to disable tips) and instead I have to disable each one as it shows up. Also, each one shows up in my notifications list in triplicate.

As I'm already working full time on Gnome 3 and have calendar events and such, these extra notifications are quite noisy. Can these be turned off somehow?

![screenshot from 2017-02-14 12-53-25](https://cloud.githubusercontent.com/assets/649798/22955692/616ae348-f2d2-11e6-8bbf-21590c3f5867.png)
![screenshot from 2017-02-14 16-23-24](https://cloud.githubusercontent.com/assets/649798/22955693/616c161e-f2d2-11e6-8471-8d8988a324f2.png)

I am using switcher installed from https://extensions.gnome.org/extension/973/switcher/ on Ubuntu GNOME 16.04.2

Thanks!

**Comment by daniellandau** [comment]
Not yet in a released version. I've been working on an improved version with a setting to completely disable them. I'll release it soon.

**Comment by cbednarski** [comment]
Thanks for the update!

**Comment by daniellandau** [comment]
The updated version is now released.

**Comment by cbednarski** [comment]
Thanks @daniellandau !
