### ISSUE TITLE
integration into activities

### ISSUE THREAD

**Issue by gdkrmr** [daniellandau/switcher#55]
would it be possible to integrate this into activities?

**Comment by daniellandau** [comment]
How do you mean? The functionality is in direct competition with activities as I see it.

**Comment by gdkrmr** [comment]
is switcher thought as a replacement for activities? one of the features i am missing from activities is being able to select a window by it's title (and selecting browser tabs), e.g. if there are 50 pdfs open.

**Comment by daniellandau** [comment]
Well not a total replacement, but a quicker way to access some of the same functionality.

Do you mean that you would like to select a window by title in activities? I can see how that would be useful, but I think it calls for a separate extension.

**Comment by gdkrmr** [comment]
is it possible to add search categories to activities with an extension? The cool part about activities is that it tries to integrate everything.

**Comment by daniellandau** [comment]
Try putting "search provider" to the search bar at https://extensions.gnome.org/ 😃

**Comment by gdkrmr** [comment]
definitely possible, sorry for the stupid question.

**Comment by daniellandau** [comment]
Nah, no stupid questions in Gnome Shell extension development.

**Comment by gdkrmr** [comment]
activities also lacks fuzzy matching :-)

**Comment by gdkrmr** [comment]
look what I found:
https://github.com/charleso/gnome-shell-extension-search-window
didn't try it yet
