### ISSUE TITLE
absolutely massive on 4k screen (and no close)

### ISSUE THREAD

**Issue by SumNeuron** [daniellandau/switcher#56]
Most applications on 4k screens are way to small; This however takes up 1/5 the screen (and with no easy Super + w again) to close is very intrusive (although otherwise a great feature)

**Comment by daniellandau** [comment]
You can configure the size in the settings.

Closing by hitting the same key combination again would be nice, and it's already tracked in https://github.com/daniellandau/switcher/issues/30.

**Comment by SumNeuron** [comment]
How do I access the settings?

**Comment by daniellandau** [comment]
Hit the settings button next to Switcher at https://extensions.gnome.org/local/

**Comment by SumNeuron** [comment]
Thank you for helping out a GNOME new comer :)

Maybe in the future make it drag-able :)

**Comment by daniellandau** [comment]
Glad to help!
