### ISSUE TITLE
'amp;' in app title after ampersand

### ISSUE THREAD

**Issue by amankhoza** [daniellandau/switcher#59]
Happens with the Ubuntu app 'Software & Updates', I'm sure this affects any app that has '&' in the title.
![screenshot from 2017-11-28 19-41-31](https://user-images.githubusercontent.com/5832764/33340595-6f1a6fac-d474-11e7-8842-3d22f251b22a.png)

I was able to fix by removing the occurrences of `.replace(/&/g, '&amp;');` in util.js, modes/launcher.js and modes/switcher.js.

![screenshot from 2017-11-28 19-49-20](https://user-images.githubusercontent.com/5832764/33340953-5a84fe9e-d475-11e7-8dd7-23cb6e6bc250.png)

**Comment by daniellandau** [comment]
This is fixed by https://github.com/daniellandau/switcher/commit/3c878ada158c802882b4c0ed5bc2684e7402b047
