### ISSUE TITLE
Please update switcher for GNOME 3.28

### ISSUE THREAD

**Issue by tareefdev** [daniellandau/switcher#61]
Please add support for GNOME 3.28

**Comment by daniellandau** [comment]
I just tried on a fresh virtual machine, and it installed and runs fine on GNOME 3.28 from Fedora beta. What kind of issue are you having?

**Comment by tareefdev** [comment]
OK, cool, I just didn't try since there is no version for gnome 3.28 in extensions.gnome.org

thanks!
