### ISSUE TITLE
Remove bottom "border" from the entry box

### ISSUE THREAD

**Issue by PHLAK** [daniellandau/switcher#62]
I'm creating a custom theme for the switcher ([available here](https://gist.github.com/PHLAK/cdce371ebbb23208c3b8c457c3925163)) and can't seem to get rid of the bottom "border" from the text entry box. How can I do this?

![screenshot from 2018-05-17 22-45-12](https://user-images.githubusercontent.com/53531/40218204-1d11b7b0-5a25-11e8-9c98-2301dbe17dab.png)

**Comment by PHLAK** [comment]
Okay, I've determined this is coming from my theme (adapta) as it's not present when using a different theme (arc).

![screenshot from 2018-05-17 22-45-12](https://user-images.githubusercontent.com/53531/40218413-f6258a72-5a25-11e8-952f-2178cb5b06c3.png)

**Comment by PHLAK** [comment]
Turns out it was a `box-shadow` and I was able to get rid of it by setting `box-shadow: none;`.

**Comment by daniellandau** [comment]
Very cool! @PHLAK how would one apply this theme? I'd love to add something to the README about theming to also resolve https://github.com/daniellandau/switcher/issues/41.

**Comment by PHLAK** [comment]
To apply this I just replaced the extension stylesheet found at `~/.local/share/gnome-shell/extensions/switcher@landau.fi/stylesheet.css`. This isn't ideal and would be nice if there was a way to add/set themes from within the Switcher settings directly.
