### ISSUE TITLE
Launch applications doesn't use any Ordering Criteria

### ISSUE THREAD

**Issue by LC43** [daniellandau/switcher#64]
Currently neither option in Ordering Criteria change the first 10 results.

Would be great if the initial list consisted of the last opened applications.

edit: i couldn't find anything recent that used a list of recent apps. But i did find an alternative: show the list of favorite apps when the launcher opens
```
const AppFavorites = imports.ui.appFavorites;
[...]
AppFavorites.getAppFavorites().getFavorites()...
```
would this be feasible to implement?

**Comment by daniellandau** [comment]
At least "last opened" meaning opened through Switcher. This is a good idea and I'm working on making opening "favorites" (that is, most opened through Switcher) faster otherwise as well.

**Comment by LC43** [comment]
thanks for looking into this!

Is Switcher you mention the default gnome thing or is your component for switching windows? tbh, i only use your Launch app and the gnome favorite bar, will does count towards the list?

**Comment by daniellandau** [comment]
Switcher is this project. Very interesting to hear that you just use the launcher part.

**Comment by daniellandau** [comment]
I just submitted a new version with (among other things) this feature. Should show up there in the near future after review.
