### ISSUE TITLE
Stops loading the translation of Gnome-Shell

### ISSUE THREAD

**Issue by xzj8b3** [daniellandau/switcher#66]
Stops loading the translation of Gnome-Shell that instead of showing up in Italian if you turn the extension comes up with various parts in English!!

Removed extension

**Comment by daniellandau** [comment]
You mean enabling Switcher disables Italian translations in unrelated parts of Gnome Shell? That sound terrible!

**Comment by xzj8b3** [comment]
Exactly after its installation I found all the user menu battery, etc. connections included in English.... as I disabled extension and I reperformed login was in English!!!

The extension is still very nice and comfortable, I would suggest integrating an option to vary colors of the theme or make it trasparent.....ad example I use transparent themes and I would really like to make transparent also the pop-up menu extension!!!!

**Comment by xzj8b3** [comment]
![schermata da 2018-07-13 16-06-42](https://user-images.githubusercontent.com/26720956/42695908-f4ec38e6-86b6-11e8-90a4-3cb5224810d5.png)


Here is an example of this happens installed just disabled extension as I re-login the menus return in Italian!!!!

transparencies manually set at line 20

How do you open the keyboard??? Alt + F2???

**Comment by xzj8b3** [comment]
![schermata da 2018-07-13 16-16-28](https://user-images.githubusercontent.com/26720956/42696416-5b2ed31a-86b8-11e8-801a-a44297694998.png)

As you see disabled extension and relogged the menu back in Italian....

It's a problem I've noticed in various extensions

**Comment by daniellandau** [comment]
Can you share your Gnome version and distribution?

**Comment by daniellandau** [comment]
I actually managed to replicate the issue with a couple of Gnome versions and distributions, so no need for that information anymore. I'll try to get it fixed as soon as possible. Thanks for reporting!

**Comment by xzj8b3** [comment]
The problem with m'è born on Fedora 28 with Gnome 3.28.2 Hopefully soon to solve is a very good extension And I really hope it's constantly maintained over time!!!!

**Comment by xzj8b3** [comment]
Very good I soon expect the release of an update to reactivate it!!!!

**Comment by daniellandau** [comment]
I uploaded to extensions.gnome.org, it takes some time before they review it and only then it's published. The latest code is here on Github and the instructions for using it are in the README if you want it sooner.

**Comment by xzj8b3** [comment]
Sure thank you very much

**Comment by xzj8b3** [comment]
Switcher is a great extension optimize and speed up the experience on Gnome... Congratulations for the work and thanks again!!!!

**Comment by daniellandau** [comment]
This has been fixed now on extensions.gnome.org so closing the issue. Thanks for reporting!
