### ISSUE TITLE
v21: JS WARNING: [.../gnome-shell/extensions/switcher@landau.fi/util.js 13]: Too many arguments to function GLib.timeout_add: expected 3, got 4

### ISSUE THREAD

**Issue by lkraav** [daniellandau/switcher#69]
I'm running on `glib-2.56.1`.

EDIT removing `setTimeout()` function `null` parameter seems to eliminates the warning message with no side effects.

**Comment by daniellandau** [comment]
Thanks. It seems that there needs to be a version check as some versions expect that and some don't.

**Comment by daniellandau** [comment]
This is fixed by https://github.com/daniellandau/switcher/commit/f70af0e7f085d0896c2ec575bdee166caec81467.
