### ISSUE TITLE
Feature request: Navigate the windows list with arrow keys (up/down)

### ISSUE THREAD

**Issue by WegDamit** [daniellandau/switcher#7]
Just a convenient feature if only a few similar windows remain after typing a few letters..

Still a very useful extension, help keeping the hand on the keyboard a lot. :)

**Comment by daniellandau** [comment]
Navigating with keyboard should work starting in a version published already a couple of months ago. Maybe you need to update? Please open another issue if you have the latest version and navigating by keyboard doesn't work.
