### ISSUE TITLE
Switcher not working on Gnome 3.30

### ISSUE THREAD

**Issue by mfaizhasan92** [daniellandau/switcher#70]
Hi, switcher not working on gnome 3.30 but app launcher is working and I'm using Arch Linux. Thanks

I think need to change this part on switcher.js:
```
let currentWorkspace = global.screen.get_active_workspace_index();
```
to
```
let workspaceManager = global.workspace_manager;
let currentWorkspace = workspaceManager.get_active_workspace();
```

**Comment by daniellandau** [comment]
Thanks for letting me know and especially for including the fix. Included in https://github.com/daniellandau/switcher/commit/475bd959dff0ce06ba087b90a89f42aa0bdafd1f.

I'll push the fix for review on extensions.gnome.org as well.
