### ISSUE TITLE
Undocumented shortcuts

### ISSUE THREAD

**Issue by thanhvg** [daniellandau/switcher#73]
There are very useful shortcuts available in the extensions but they are not documented.
- C-j for enter, 
- C-m for switching between mode
- C-h for backspace
- C-p and C-n for up and down 

These shortcuts are very useful and should be mentioned in the doc. 

If  we agree I would also like to create a PR to map C-j and C-k to up and down, and C-g to enter.

**Comment by daniellandau** [comment]
Those are there mainly to be delightful surprises to people who have muscle memory from vi or emacs. I wouldn't change the definition of C-j as the current one is the same as it is in both vi and emacs. C-g is emacs for cancel, so it would be quite confusing to have that be enter.

I agree that these could be documented, but I don't have a clear idea what would be a good place for that. There are the tips, but I don't think enough people would care about these to put in there.

**Comment by manuel-uberti** [comment]
As an Emacs, I can only add "Please don't change C-j and C-g!" to this. :smile:

**Comment by thanhvg** [comment]
I close this since it's not a popular idea and conflicts with @daniellandau's design
