### ISSUE TITLE
Chinese input method support

### ISSUE THREAD

**Issue by nlpsuge** [daniellandau/switcher#75]
When type with Chinese input method(ibus-rime-1.3.0), press Enter just go to the first window directly. But I want letters should be shown in Switcher.

A workaround: press Shift or switch to English input method before typing any character.

**Comment by daniellandau** [comment]
Hmm. I want Switcher to work with Chinese, but I need to look into how the input method works a bit before I can estimate how easy/hard that is. Does the normal Gnome Shell overview search work as expected?

**Comment by nlpsuge** [comment]
Yes, Gnome Shell overview works as expected. I can input letter(s)  into search box by pressing Enter with Chinese input method.

By the way, another Gnome extension named Todo.txt(https://extensions.gnome.org/extension/570/todotxt/) has the same issue too, when I try to modify an item.

**Comment by daniellandau** [comment]
So I can find two errors:

1. When hitting enter after some letters, the English letters should be input to the text field, list should be filtered and no app should be activated
2. When selecting Chinese characters with mouse, the list is not updated, but is only updated after hitting another key, for example the space bar. Hitting a number to select a Chinese character works as expected.

Can you confirm that these are the issues? Are there any other that you have found?

I don't have a fix for these yet, but knowing what the issue is and being able to reproduce it is already a good start.

**Comment by nlpsuge** [comment]
Yes, I can confirm that those two are issues.

No, I only found the first one error, and you found the second. I will notice during using Switcher.

You are so careful, thanks.

**Comment by daniellandau** [comment]
I'm leaving problem number 2. go unsolved for now, as that doesn't work in Shell overview either (in fact, works even worse there). I already have a version sitting in review at extensions.gnome.org, so I'll submit this fix after that one gets through. Meanwhile you can get the latest version with the directions in the README.

**Comment by nlpsuge** [comment]
Hi @daniellandau ,

I think this issue has been reoccurred. 
Should I reopen it?

**Comment by daniellandau** [comment]
Does chinese input method work for you in the normal Gnome Shell overview now? For me that is broken too as I try it.

**Comment by nlpsuge** [comment]
No, it does not work either in the Overview.

And cannot type into any Chinese characters.

Maybe is this a issue linked to Gnome Shell itself?

**Comment by daniellandau** [comment]
This seems to be an issue with gnome shell, please report it to https://gitlab.gnome.org/GNOME/gnome-shell/

Let's keep this issue open until it's fixed, but at the moment I can't do much about it.

**Comment by nlpsuge** [comment]
Here is a related issue and I add a comment there:
https://gitlab.gnome.org/GNOME/mutter/-/issues/1413#note_908581

**Comment by nlpsuge** [comment]
This issue has been fixed in recent updates.
