### ISSUE TITLE
[Fedora 30; Gnome 3.32.2] Switcher suddenly flagged as under error.

### ISSUE THREAD

**Issue by businessBoris** [daniellandau/switcher#82]
Switcher has suddenly gained an error status (on the gnome extension webpage and gnome tweaks application). I'm somewhat surprised because there's no obvious reason like a major change in gnome version etc. None of my other extensions are flagged as having problems.

I don't remember how to give you the error information that you would need to help. Please would someone point me in the right direction and I'll websearch the rest.

No-one else is having problems according to this issues list so perhaps my end.

Thank you in advance.

**Comment by daniellandau** [comment]
Are you still having this issue?

**Comment by businessBoris** [comment]
I am, sir. I'm not near my desktop at the moment. I'll update this issue when I can. Anything else I can give you?

**Comment by businessBoris** [comment]
Yes, sadly. Will update when near workstation.

**Comment by businessBoris** [comment]
New install gives:

```
JS ERROR: Extension switcher@landau.fi: TypeError: deps is not a function
                                          @/home/*/.local/share/gnome-shell/extensions/switcher@landau.fi/promise.js:24:47
                                          @/home/*/.local/share/gnome-shell/extensions/switcher@landau.fi/promise.js:22:2
                                          @/home/*/.local/share/gnome-shell/extensions/switcher@landau.fi/extension.js:38:7

```

**Comment by daniellandau** [comment]
I tried with a Fedore 30 virtual machine and couldn't replicate your problem.

Can you share what other extensions you have installed, or try disabling them all to see if that helps?

**Comment by businessBoris** [comment]
Hi Daniel,

Switcher is known to work faultlessly on Fedora 30. We're now on 31. Which version of gnome are you running on the VM?
That said, I just realised that I hadn't restarted Gnome when I reinstalled Switcher. Doh!

**Comment by daniellandau** [comment]
I tested also on Fedora 31, no issues there either.

**Comment by daniellandau** [comment]
Please open a new issue if there's still a problem.
