### ISSUE TITLE
When on gnome 3.34

### ISSUE THREAD

**Issue by xzj8b3** [daniellandau/switcher#83]
When on gnome 3.34?? 

I love this extension now.

**Comment by daniellandau** [comment]
In principle it works already, but sometimes the hot key is not enabled after logging in, and requires a shell restart before being enabled. I'd like to find an answer to that before declaring compatibility.

In the mean time you can use the extension through the instructions on the README (possibly first changing metadata.json to add 3.34 if your distro requires it).

**Comment by xzj8b3** [comment]
> In principle it works already, but sometimes the hot key is not enabled after logging in, and requires a shell restart before being enabled. I'd like to find an answer to that before declaring compatibility.
> 
> In the mean time you can use the extension through the instructions on the README (possibly first changing metadata.json to add 3.34 if your distro requires it).

Tenks

**Comment by businessBoris** [comment]
Thanks @daniellandau.

**Comment by daniellandau** [comment]
It's up for review at extensions.gnome.org now. @businessBoris if your error persists, please open a new issue.
