### ISSUE TITLE
Sound or Wifi under settings

### ISSUE THREAD

**Issue by frizop** [daniellandau/switcher#84]
Is it possible to have switcher dig into the settings panel and present things like WIFI or sound? You can do this with Activities overview already

**Comment by esauvisky** [comment]
There's a fork from @goodwillcoding that does exactly that, highly recommended:
https://github.com/goodwillcoding/switcher/tree/gnome-control-panel

Just delete your `switcher@landau.fi` original directory and run:
```sh
git clone -b gnome-control-panel https://github.com/goodwillcoding/switcher.git switcher@landau.fi
```

**Comment by daniellandau** [comment]
@goodwillcoding reported some instabilities and issues with that branch (see discussion on https://github.com/daniellandau/switcher/pull/81), so if you do use it I'd appreciate some more data on which types of systems (distros etc) it works or doesn't work reliably on.
