### ISSUE TITLE
Option to also use activation hotkey to navigate to next window

### ISSUE THREAD

**Issue by seanh** [daniellandau/switcher#87]
I configure Switcher in a way that allows switching windows _without hitting multiple keys at once_, which I like because my RSI makes it a pain to hold down one key while tapping another (e.g. <kbd><kbd>Alt</kbd> + <kbd>Tab</kbd></kbd>).

* I set <kbd>F12</kbd> as the hotkey to activate switcher
* I can now switch windows with a key sequence like this: <kbd><kbd>F12</kbd> [<kbd>Tab</kbd>] ... <kbd>Enter</kbd></kbd>. That is: I hit <kbd>F12</kbd> once to activate Switcher, if the window I want to switch to isn't the first selected one I then hit <kbd>Tab</kbd> one or more times to get to the window that I want, then finally I hit <kbd>Enter</kbd> to switch to the window.

It would be nicer if I could use <kbd>F12</kbd> instead of <kbd>Tab</kbd> to go to the next window. So <kbd>F12</kbd> would activate Switcher or, if Switcher is already activated, <kbd>F12</kbd> would go to the next window in Switcher. Then instead of <kbd><kbd>F12</kbd> <kbd>Tab</kbd> <kbd>Tab</kbd> <kbd>Tab</kbd> <kbd>Enter</kbd></kbd> I could just do <kbd><kbd>F12</kbd> <kbd>F12</kbd> <kbd>F12</kbd> <kbd>F12</kbd> <kbd>Enter</kbd></kbd>, which is much easier.

**Comment by daniellandau** [comment]
I'm not sure that's a feature wanted by many users. For your specific use case it's a very easy edit that you can make to `extension.js` after line 234 (`symbol === Clutter.KEY_Tab ||`) add `symbol === Clutter.KEY_F12 ||` and add `&& false` to the end of line 281 to prevent repeat hot key from closing Switcher.
