### ISSUE TITLE
[Feature Request] custom hotkey to switch between launcher and switcher and custom font size in input box

### ISSUE THREAD

**Issue by tuberry** [daniellandau/switcher#89]
It's inconvenient for someone who use `Ctrl+Space` or `Ctrl+Tab` to launch or switch exclusively. And the font size of input box is too small in contrast to the entries.

**Comment by daniellandau** [comment]
I'm not sure I follow what you mean.
For me the font sizes are about the same for input box and entries. What distribution are you using?

**Comment by tuberry** [comment]
OK, they are the same when using default shell theme, but not for the others like [Materia](https://github.com/nana-4/materia-theme). Thanks.

**Comment by tuberry** [comment]
I notice that's too small in Materia and big in Adapta. Which filed does Switcher use for input box.
