### ISSUE TITLE
Hi, but when do you release Switcher for Gnome 3.34?

### ISSUE THREAD

**Issue by xzj8b3** [daniellandau/switcher#91]
Hi, I was wondering why so much delay in releasing Switcher that I look forward to its comfort, can you tell me something about please ?

**Comment by daniellandau** [comment]
There was issues with hotkey activation when 3.34 was just out, but I haven't seen that lately so has been hopefully fixed in Gnome Shell. It's up for review at extensions.gnome.org now.
