### ISSUE TITLE
Switcher to Appear on Screen with Last Active Window or Follows Mouse?

### ISSUE THREAD

**Issue by trst** [daniellandau/switcher#92]
I have multiple screens and switcher opens on the Primary display. I wonder if it would be better if the location that Switcher appeared either opens on the display where the current active window is, or perhaps follows the mouse. Obviously, when there's only one display, then switcher appears only on that display.

Maybe those options are user settings?

**Comment by daniellandau** [comment]
That's not really a use case I have, so I wouldn't feel comfortable testing the UX to be right. Maybe someone can contribute such a mode?
