### ISSUE TITLE
Doesn't work anymore with Gnome 3.36

### ISSUE THREAD

**Issue by chrisime** [daniellandau/switcher#97]
After upgrading to Gnome 3.36 the extension no longer works.

**Comment by pstonham** [comment]
`JS ERROR: TypeError: tmpContainer.set_alignment is not a function
                                         _showUI/containers<@/home/user/.local/share/gnome-shell/extensions/switcher@landau.fi/extension.js:157:22`

**Comment by daniellandau** [comment]
Thanks for letting me know, I'll try to get that fixed before 3.36 is released.

**Comment by felipehw** [comment]
Thanks. This extension is wonderful and I can't live without it :D

**Comment by daniellandau** [comment]
Ah, I was only checking gnome.org front page. Turns out that 3.36 was released already last Sunday (my time zone). I'll try to get this fixed ASAP (and help also appreciated if someone is quicker to the fix)

**Comment by mfaizhasan** [comment]
Hi, I  don't know this would help or not but I did something to the code :-
extension.js
`
let tmpContainer = new St.Bin({ reactive: true });
//tmpContainer.set_alignment(St.Align.MIDDLE, St.Align.START);
tmpContainer.set_width(monitor.width);
tmpContainer.set_height(monitor.height);
tmpContainer.set_position(monitor.x, monitor.y);
`
I comment out that part how the switcher able to open again but the alignment is off. I unable to find Api Docs for St.Bin, well I'm out of luck hahah.

**Comment by daniellandau** [comment]
It seems coding a fix is easier/faster for me right now than getting a 3.36 virtual machine going. There's a potential fix in https://github.com/daniellandau/switcher/commit/028c46febc0b9ee7fdefa5c1cd909ed2d9b86151 (branch alignment-fix-for-gnome-3.36), could someone give it a try?

The best documentation is the source code, at https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/src/st/st-bin.h, where the most recent commit is "st: Remove StBin's align properties"

**Comment by pstonham** [comment]
Yeah that's working for me, it stretches across the whole screen but it's working, nice one.
![Screenshot from 2020-03-13 09-36-17](https://user-images.githubusercontent.com/1978911/76608785-26048780-650e-11ea-8a63-ff0c0eea5195.png)

**Comment by mans82** [comment]
I don't really know much about making a Gnome extension, but I tried tinkering the source code, and looks like removing `set_width()` and `set_height()` ([These lines](https://github.com/daniellandau/switcher/blob/f3408c7744686665aae176335ef84b6707b35e13/extension.js#L158)) fixes the size, no longer stretching it across the screen.
It's not correctly aligned, though.

![image](https://user-images.githubusercontent.com/39344547/76621887-a2ff2380-6545-11ea-8576-12fd9a7111f0.png)

Hope this helps.

**Comment by daniellandau** [comment]
The container needs to have those widths and heights because it's the invisible part that makes sure that switcher goes away if the user clicks outside the switcher.

I was trying stuff out in an Ubuntu 20.04 VM, but that was quite broken when I tried it, for example extension settings was totally nonfunctional. My Arch host just got 3.36 so I'll try to get this fixed asap. With the change in the branch it already works, but with the visual glitch you see on pstonham's screen shot. If I can't figure out that fix, I'll just release the partially glitchy version in e.g.o just for 3.36 later today.

**Comment by daniellandau** [comment]
Ok, in the review queue now, sadly with the visual glitch.

**Comment by daniellandau** [comment]
Released.
