### ISSUE TITLE
Size of the pop-up window is out of control in gnome-shell 3.36

### ISSUE THREAD

**Issue by danleepw** [daniellandau/switcher#98]
The pop-up window cover almost the full display.

![Screenshot from 2020-03-25](https://user-images.githubusercontent.com/10960592/77454234-36cccb80-6e33-11ea-8573-ad30e7a98627.jpg)

**Comment by daniellandau** [comment]
I had to rush a fix for https://github.com/daniellandau/switcher/issues/97 before finding a fix for this. It's now fixed in master and pending review at extensions.gnome.org.
